name: Main Performance PC - TV
favicon: null
layout_spectrum: 1
typography_spectrum: 0.85484
title: 'The Official Source for Information & Tech Content from MPPC'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1e1e1e'
    - '#0061ec'
    - '#929292'
    - '#5d5d5d'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
